build:
  maxIssues: 0

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "_|(ignore|expected).*"
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    active: true
    constantPattern: "[A-Z][_A-Z0-9]*"

performance:
  active: true
  ArrayPrimitive:
    active: true
  SpreadOperator:
    active: true

potential-bugs:
  active: true
  DontDowncastCollectionTypes:
    active: true
  ImplicitUnitReturnType:
    active: true
  UnreachableCode:
    active: true

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
    ignoreAnnotated:
      - "Preview"
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - "Preview"
  WildcardImport:
    active: true
    excludeImports:
      - "kotlinx.android.synthetic.*"

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: false
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: false
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: false
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
